services:
  grobid-software-mentions:
    image: "grobid/software-mentions:0.8.0"
    ports:
      - "8060:8060"
    init: true
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ulimits:
      core:
        soft: 0
        hard: 0

  software-mentions-processing:
    build: .
    container_name: software-mentions-processing
    volumes:
      - ./data/:/soft-proc/data/
    command: sleep infinity
    network_mode: service:grobid-software-mentions